### ISSUE TITLE
Error when modify No.12's Order

### ISSUE THREAD

**Issue by fishren** [alvachien/achihui#107]
Error occurred when modify No.12's Order's end date. 
"Not Found;null;http failure response for http://118.178.58.187:5300/api/FinanceOrder:404
Not Found"

**Comment by alvachien** [comment]
#https://github.com/alvachien/achihapi/issues/17

**Comment by alvachien** [comment]
Fixed with commit https://github.com/alvachien/achihui/commit/2608ed564084c3ffc05e4cdbd9b3505d0a8daa76
